_wandb:
    value:
        cli_version: 0.21.0
        e:
            htkovo351rkrn5p5ao6gpzgfa01076pv:
                codePath: main.py
                codePathLocal: main.py
                cpu_count: 64
                cpu_count_logical: 64
                cudaVersion: "12.8"
                disk:
                    /:
                        total: "4261618229248"
                        used: "70206840832"
                email: wguo6358@gmail.com
                executable: /home/ubuntu/wash/miniconda3/bin/python3
                gpu: NVIDIA GH200 480GB
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Hopper
                      cudaCores: 16896
                      memoryTotal: "102625181696"
                      name: NVIDIA GH200 480GB
                      uuid: GPU-df2e6bc2-a15a-acb6-b810-c540bf29a8a2
                host: 192-222-59-219
                memory:
                    total: "564443283456"
                os: Linux-6.8.0-1013-nvidia-64k-aarch64-with-glibc2.35
                program: /lambda/nfs/wash/scores/main.py
                python: CPython 3.13.5
                root: /lambda/nfs/wash/scores
                startedAt: "2025-10-12T05:07:14.348170Z"
                writerId: htkovo351rkrn5p5ao6gpzgfa01076pv
        m: []
        python_version: 3.13.5
        t:
            "1":
                - 1
                - 11
                - 41
                - 49
                - 51
                - 71
                - 83
                - 98
                - 105
            "2":
                - 1
                - 11
                - 41
                - 49
                - 51
                - 63
                - 71
                - 83
                - 98
                - 105
            "4": 3.13.5
            "5": 0.21.0
            "6": 4.56.2
            "12": 0.21.0
            "13": linux-aarch64
